/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 20220523
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AbilityListParams,
  BerryFirmnessListParams,
  BerryFlavorListParams,
  BerryListParams,
  CharacteristicListParams,
  ContestEffectListParams,
  ContestTypeListParams,
  EggGroupListParams,
  EncounterConditionListParams,
  EncounterConditionValueListParams,
  EncounterMethodListParams,
  EvolutionChainListParams,
  EvolutionTriggerListParams,
  GenderListParams,
  GenerationListParams,
  GrowthRateListParams,
  ItemAttributeListParams,
  ItemCategoryListParams,
  ItemFlingEffectListParams,
  ItemListParams,
  ItemPocketListParams,
  LanguageListParams,
  LocationAreaListParams,
  LocationListParams,
  MachineListParams,
  MoveAilmentListParams,
  MoveBattleStyleListParams,
  MoveCategoryListParams,
  MoveDamageClassListParams,
  MoveLearnMethodListParams,
  MoveListParams,
  MoveTargetListParams,
  NatureListParams,
  PalParkAreaListParams,
  PokeathlonStatListParams,
  PokedexListParams,
  PokemonColorListParams,
  PokemonFormListParams,
  PokemonHabitatListParams,
  PokemonListParams,
  PokemonShapeListParams,
  PokemonSpeciesListParams,
  RegionListParams,
  StatListParams,
  SuperContestEffectListParams,
  TypeListParams,
  VersionGroupListParams,
  VersionListParams
} from '../api/generated';

export const abilityList = <TData = AxiosResponse<string>>(
    params?: AbilityListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/ability/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const abilityRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/ability/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const berryFirmnessList = <TData = AxiosResponse<string>>(
    params?: BerryFirmnessListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/berry-firmness/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const berryFirmnessRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/berry-firmness/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const berryFlavorList = <TData = AxiosResponse<string>>(
    params?: BerryFlavorListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/berry-flavor/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const berryFlavorRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/berry-flavor/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const berryList = <TData = AxiosResponse<string>>(
    params?: BerryListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/berry/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const berryRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/berry/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const characteristicList = <TData = AxiosResponse<string>>(
    params?: CharacteristicListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/characteristic/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const characteristicRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/characteristic/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const contestEffectList = <TData = AxiosResponse<string>>(
    params?: ContestEffectListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/contest-effect/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const contestEffectRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/contest-effect/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const contestTypeList = <TData = AxiosResponse<string>>(
    params?: ContestTypeListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/contest-type/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const contestTypeRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/contest-type/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const eggGroupList = <TData = AxiosResponse<string>>(
    params?: EggGroupListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/egg-group/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const eggGroupRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/egg-group/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const encounterConditionValueList = <TData = AxiosResponse<string>>(
    params?: EncounterConditionValueListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/encounter-condition-value/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const encounterConditionValueRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/encounter-condition-value/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const encounterConditionList = <TData = AxiosResponse<string>>(
    params?: EncounterConditionListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/encounter-condition/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const encounterConditionRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/encounter-condition/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const encounterMethodList = <TData = AxiosResponse<string>>(
    params?: EncounterMethodListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/encounter-method/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const encounterMethodRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/encounter-method/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const evolutionChainList = <TData = AxiosResponse<string>>(
    params?: EvolutionChainListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/evolution-chain/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const evolutionChainRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/evolution-chain/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const evolutionTriggerList = <TData = AxiosResponse<string>>(
    params?: EvolutionTriggerListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/evolution-trigger/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const evolutionTriggerRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/evolution-trigger/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const genderList = <TData = AxiosResponse<string>>(
    params?: GenderListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/gender/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const genderRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/gender/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const generationList = <TData = AxiosResponse<string>>(
    params?: GenerationListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/generation/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const generationRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/generation/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const growthRateList = <TData = AxiosResponse<string>>(
    params?: GrowthRateListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/growth-rate/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const growthRateRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/growth-rate/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const itemAttributeList = <TData = AxiosResponse<string>>(
    params?: ItemAttributeListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/item-attribute/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const itemAttributeRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/item-attribute/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const itemCategoryList = <TData = AxiosResponse<string>>(
    params?: ItemCategoryListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/item-category/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const itemCategoryRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/item-category/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const itemFlingEffectList = <TData = AxiosResponse<string>>(
    params?: ItemFlingEffectListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/item-fling-effect/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const itemFlingEffectRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/item-fling-effect/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const itemPocketList = <TData = AxiosResponse<string>>(
    params?: ItemPocketListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/item-pocket/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const itemPocketRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/item-pocket/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const itemList = <TData = AxiosResponse<string>>(
    params?: ItemListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/item/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const itemRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/item/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const languageList = <TData = AxiosResponse<string>>(
    params?: LanguageListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/language/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const languageRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/language/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const locationAreaList = <TData = AxiosResponse<string>>(
    params?: LocationAreaListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/location-area/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const locationAreaRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/location-area/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const locationList = <TData = AxiosResponse<string>>(
    params?: LocationListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/location/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const locationRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/location/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const machineList = <TData = AxiosResponse<string>>(
    params?: MachineListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/machine/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const machineRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/machine/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const moveAilmentList = <TData = AxiosResponse<string>>(
    params?: MoveAilmentListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/move-ailment/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const moveAilmentRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/move-ailment/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const moveBattleStyleList = <TData = AxiosResponse<string>>(
    params?: MoveBattleStyleListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/move-battle-style/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const moveBattleStyleRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/move-battle-style/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const moveCategoryList = <TData = AxiosResponse<string>>(
    params?: MoveCategoryListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/move-category/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const moveCategoryRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/move-category/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const moveDamageClassList = <TData = AxiosResponse<string>>(
    params?: MoveDamageClassListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/move-damage-class/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const moveDamageClassRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/move-damage-class/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const moveLearnMethodList = <TData = AxiosResponse<string>>(
    params?: MoveLearnMethodListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/move-learn-method/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const moveLearnMethodRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/move-learn-method/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const moveTargetList = <TData = AxiosResponse<string>>(
    params?: MoveTargetListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/move-target/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const moveTargetRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/move-target/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const moveList = <TData = AxiosResponse<string>>(
    params?: MoveListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/move/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const moveRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/move/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const natureList = <TData = AxiosResponse<string>>(
    params?: NatureListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/nature/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const natureRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/nature/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const palParkAreaList = <TData = AxiosResponse<string>>(
    params?: PalParkAreaListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/pal-park-area/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const palParkAreaRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/pal-park-area/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const pokeathlonStatList = <TData = AxiosResponse<string>>(
    params?: PokeathlonStatListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/pokeathlon-stat/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const pokeathlonStatRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/pokeathlon-stat/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const pokedexList = <TData = AxiosResponse<string>>(
    params?: PokedexListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/pokedex/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const pokedexRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/pokedex/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const pokemonColorList = <TData = AxiosResponse<string>>(
    params?: PokemonColorListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/pokemon-color/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const pokemonColorRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/pokemon-color/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const pokemonFormList = <TData = AxiosResponse<string>>(
    params?: PokemonFormListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/pokemon-form/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const pokemonFormRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/pokemon-form/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const pokemonHabitatList = <TData = AxiosResponse<string>>(
    params?: PokemonHabitatListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/pokemon-habitat/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const pokemonHabitatRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/pokemon-habitat/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const pokemonShapeList = <TData = AxiosResponse<string>>(
    params?: PokemonShapeListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/pokemon-shape/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const pokemonShapeRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/pokemon-shape/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const pokemonSpeciesList = <TData = AxiosResponse<string>>(
    params?: PokemonSpeciesListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/pokemon-species/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const pokemonSpeciesRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/pokemon-species/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const pokemonList = <TData = AxiosResponse<string>>(
    params?: PokemonListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/pokemon/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const pokemonRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/pokemon/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const regionList = <TData = AxiosResponse<string>>(
    params?: RegionListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/region/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const regionRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/region/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const statList = <TData = AxiosResponse<string>>(
    params?: StatListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/stat/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const statRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/stat/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const superContestEffectList = <TData = AxiosResponse<string>>(
    params?: SuperContestEffectListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/super-contest-effect/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const superContestEffectRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/super-contest-effect/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const typeList = <TData = AxiosResponse<string>>(
    params?: TypeListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/type/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const typeRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/type/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const versionGroupList = <TData = AxiosResponse<string>>(
    params?: VersionGroupListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/version-group/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const versionGroupRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/version-group/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export const versionList = <TData = AxiosResponse<string>>(
    params?: VersionListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/version/`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const versionRead = <TData = AxiosResponse<string>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v2/version/${id}/`,{
        responseType: 'text',
    ...options,}
    );
  }

export type AbilityListResult = AxiosResponse<string>
export type AbilityReadResult = AxiosResponse<string>
export type BerryFirmnessListResult = AxiosResponse<string>
export type BerryFirmnessReadResult = AxiosResponse<string>
export type BerryFlavorListResult = AxiosResponse<string>
export type BerryFlavorReadResult = AxiosResponse<string>
export type BerryListResult = AxiosResponse<string>
export type BerryReadResult = AxiosResponse<string>
export type CharacteristicListResult = AxiosResponse<string>
export type CharacteristicReadResult = AxiosResponse<string>
export type ContestEffectListResult = AxiosResponse<string>
export type ContestEffectReadResult = AxiosResponse<string>
export type ContestTypeListResult = AxiosResponse<string>
export type ContestTypeReadResult = AxiosResponse<string>
export type EggGroupListResult = AxiosResponse<string>
export type EggGroupReadResult = AxiosResponse<string>
export type EncounterConditionValueListResult = AxiosResponse<string>
export type EncounterConditionValueReadResult = AxiosResponse<string>
export type EncounterConditionListResult = AxiosResponse<string>
export type EncounterConditionReadResult = AxiosResponse<string>
export type EncounterMethodListResult = AxiosResponse<string>
export type EncounterMethodReadResult = AxiosResponse<string>
export type EvolutionChainListResult = AxiosResponse<string>
export type EvolutionChainReadResult = AxiosResponse<string>
export type EvolutionTriggerListResult = AxiosResponse<string>
export type EvolutionTriggerReadResult = AxiosResponse<string>
export type GenderListResult = AxiosResponse<string>
export type GenderReadResult = AxiosResponse<string>
export type GenerationListResult = AxiosResponse<string>
export type GenerationReadResult = AxiosResponse<string>
export type GrowthRateListResult = AxiosResponse<string>
export type GrowthRateReadResult = AxiosResponse<string>
export type ItemAttributeListResult = AxiosResponse<string>
export type ItemAttributeReadResult = AxiosResponse<string>
export type ItemCategoryListResult = AxiosResponse<string>
export type ItemCategoryReadResult = AxiosResponse<string>
export type ItemFlingEffectListResult = AxiosResponse<string>
export type ItemFlingEffectReadResult = AxiosResponse<string>
export type ItemPocketListResult = AxiosResponse<string>
export type ItemPocketReadResult = AxiosResponse<string>
export type ItemListResult = AxiosResponse<string>
export type ItemReadResult = AxiosResponse<string>
export type LanguageListResult = AxiosResponse<string>
export type LanguageReadResult = AxiosResponse<string>
export type LocationAreaListResult = AxiosResponse<string>
export type LocationAreaReadResult = AxiosResponse<string>
export type LocationListResult = AxiosResponse<string>
export type LocationReadResult = AxiosResponse<string>
export type MachineListResult = AxiosResponse<string>
export type MachineReadResult = AxiosResponse<string>
export type MoveAilmentListResult = AxiosResponse<string>
export type MoveAilmentReadResult = AxiosResponse<string>
export type MoveBattleStyleListResult = AxiosResponse<string>
export type MoveBattleStyleReadResult = AxiosResponse<string>
export type MoveCategoryListResult = AxiosResponse<string>
export type MoveCategoryReadResult = AxiosResponse<string>
export type MoveDamageClassListResult = AxiosResponse<string>
export type MoveDamageClassReadResult = AxiosResponse<string>
export type MoveLearnMethodListResult = AxiosResponse<string>
export type MoveLearnMethodReadResult = AxiosResponse<string>
export type MoveTargetListResult = AxiosResponse<string>
export type MoveTargetReadResult = AxiosResponse<string>
export type MoveListResult = AxiosResponse<string>
export type MoveReadResult = AxiosResponse<string>
export type NatureListResult = AxiosResponse<string>
export type NatureReadResult = AxiosResponse<string>
export type PalParkAreaListResult = AxiosResponse<string>
export type PalParkAreaReadResult = AxiosResponse<string>
export type PokeathlonStatListResult = AxiosResponse<string>
export type PokeathlonStatReadResult = AxiosResponse<string>
export type PokedexListResult = AxiosResponse<string>
export type PokedexReadResult = AxiosResponse<string>
export type PokemonColorListResult = AxiosResponse<string>
export type PokemonColorReadResult = AxiosResponse<string>
export type PokemonFormListResult = AxiosResponse<string>
export type PokemonFormReadResult = AxiosResponse<string>
export type PokemonHabitatListResult = AxiosResponse<string>
export type PokemonHabitatReadResult = AxiosResponse<string>
export type PokemonShapeListResult = AxiosResponse<string>
export type PokemonShapeReadResult = AxiosResponse<string>
export type PokemonSpeciesListResult = AxiosResponse<string>
export type PokemonSpeciesReadResult = AxiosResponse<string>
export type PokemonListResult = AxiosResponse<string>
export type PokemonReadResult = AxiosResponse<string>
export type RegionListResult = AxiosResponse<string>
export type RegionReadResult = AxiosResponse<string>
export type StatListResult = AxiosResponse<string>
export type StatReadResult = AxiosResponse<string>
export type SuperContestEffectListResult = AxiosResponse<string>
export type SuperContestEffectReadResult = AxiosResponse<string>
export type TypeListResult = AxiosResponse<string>
export type TypeReadResult = AxiosResponse<string>
export type VersionGroupListResult = AxiosResponse<string>
export type VersionGroupReadResult = AxiosResponse<string>
export type VersionListResult = AxiosResponse<string>
export type VersionReadResult = AxiosResponse<string>
