import { Archivo_Black, Space_Grotesk } from 'next/font/google';

import './globals.css';

import { QueryProvider } from '@/components/providers/query-provider';

import type { Metadata } from 'next';

const archivoBlack = Archivo_Black({
  display: 'swap',
  subsets: ['latin'],
  variable: '--font-head',
  weight: '400',
});

const space = Space_Grotesk({
  display: 'swap',
  subsets: ['latin'],
  variable: '--font-sans',
  weight: '400',
});

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang='en'>
      <body className={`${archivoBlack.variable} ${space.variable}`}>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
};

export default RootLayout;
