/**
 * Script to generate custom hooks with automatic JSON parsing
 * This script should be run after Orval generates the base hooks
 */

import { readFileSync, writeFileSync, readdirSync, statSync } from 'fs';
import { join } from 'path';

const GENERATED_DIR = './src/api/generated';
const HOOKS_DIR = './src/api/hooks';

/**
 * Map of operation IDs to their corresponding model types
 */
const OPERATION_TO_MODEL = {
  pokemon_read: { model: 'Pokemon', importPath: '../../../api/models/Pokemon' },
  pokemon_list: { model: 'NamedAPIResourceList', importPath: '../../../api/models/Common' },
  // Add more mappings as needed
};

/**
 * Extract model type from operation ID
 */
function getModelType(operationId) {
  if (OPERATION_TO_MODEL[operationId]) {
    return OPERATION_TO_MODEL[operationId];
  }
  return null;
}

/**
 * Generate hook file content
 */
function generateHookFile(operationId, hookName, baseHookName, params, modelType) {
  const isList = operationId.endsWith('_list');
  // Extract parameter name (remove type and optional marker)
  const paramName = params.split(':')[0].replace('?', '').trim();
  
  return `/**
 * Auto-generated hook with automatic JSON parsing
 * Generated from operation: ${operationId}
 * DO NOT EDIT MANUALLY - This file is generated by scripts/generate-hooks.mjs
 */

import { ${baseHookName} } from '@/api/generated';
import type { ${modelType.model} } from '${modelType.importPath}';
import { parseApiResponse } from '@/api/utils';
${isList ? "import type { PokemonListParams } from '../../../api/generated';" : ''}

/**
 * Hook for ${operationId} with automatic JSON parsing
 * @param ${params}
 * @returns React Query result with parsed ${modelType.model} data
 */
export function ${hookName}(${params}) {
  return ${baseHookName}(${paramName}, {
    query: {
      select: (data) => parseApiResponse<${modelType.model}>(data),
    },
  });
}
`;
}

/**
 * Process pokemon.ts file and generate hooks
 */
function processPokemonFile() {
  const filePath = join(GENERATED_DIR, 'pokemon/pokemon.ts');
  const content = readFileSync(filePath, 'utf-8');
  
  // Generate usePokemon hook
  const usePokemonContent = generateHookFile(
    'pokemon_read',
    'usePokemon',
    'usePokemonRead',
    'pokemonId: number',
    { model: 'Pokemon', importPath: '../../../api/models/Pokemon' }
  );
  
  // Generate usePokemonListParsed hook
  const usePokemonListContent = generateHookFile(
    'pokemon_list',
    'usePokemonListParsed',
    'usePokemonList',
    'params?: PokemonListParams',
    { model: 'NamedAPIResourceList', importPath: '../../../api/models/Common' }
  );
  
  // Combine both hooks with deduplicated imports
  const combinedContent = `/**
 * Auto-generated hooks with automatic JSON parsing
 * DO NOT EDIT MANUALLY - This file is generated by scripts/generate-hooks.mjs
 * Run: npm run generate-hooks
 */

import { usePokemonRead, usePokemonList } from '@/api/generated';
import type { Pokemon } from '../../../api/models/Pokemon';
import type { NamedAPIResourceList } from '../../../api/models/Common';
import type { PokemonListParams } from '../../../api/generated';
import { parseApiResponse } from '@/api/utils';

/**
 * Hook for pokemon_read with automatic JSON parsing
 * @param pokemonId - The ID of the Pokemon to fetch
 * @returns React Query result with parsed Pokemon data
 */
export function usePokemon(pokemonId: number) {
  return usePokemonRead(pokemonId, {
    query: {
      select: (data) => parseApiResponse<Pokemon>(data),
    },
  });
}

/**
 * Hook for pokemon_list with automatic JSON parsing
 * @param params - Query parameters for the Pokemon list
 * @returns React Query result with parsed NamedAPIResourceList data
 */
export function usePokemonListParsed(params?: PokemonListParams) {
  return usePokemonList(params, {
    query: {
      select: (data) => parseApiResponse<NamedAPIResourceList>(data),
    },
  });
}
`;
  
  const hookFilePath = join(HOOKS_DIR, 'use-pokemon.generated.ts');
  writeFileSync(hookFilePath, combinedContent);
  console.log(`✓ Generated hooks: ${hookFilePath}`);
}

/**
 * Main function
 */
function main() {
  console.log('Generating custom hooks with automatic JSON parsing...\n');
  
  try {
    processPokemonFile();
    console.log('\n✓ Done!');
  } catch (error) {
    console.error('Error generating hooks:', error);
    process.exit(1);
  }
}

main();

