/**
 * Auto-generated hooks with automatic JSON parsing
 * DO NOT EDIT MANUALLY - This file is generated by scripts/generate-hooks.mjs
 * Run: npm run generate-hooks
 */

import { usePokemonRead, usePokemonList } from '@/api/generated';
import type { Pokemon } from '../../../api/models/Pokemon';
import type { NamedAPIResourceList } from '../../../api/models/Common';
import type { PokemonListParams } from '../../../api/generated';
import { parseApiResponse } from '@/api/utils';

/**
 * Hook for pokemon_read with automatic JSON parsing
 * @param pokemonId - The ID of the Pokemon to fetch
 * @returns React Query result with parsed Pokemon data
 */
export function usePokemon(pokemonId: number) {
  return usePokemonRead(pokemonId, {
    query: {
      select: (data) => parseApiResponse<Pokemon>(data),
    },
  });
}

/**
 * Hook for pokemon_list with automatic JSON parsing
 * @param params - Query parameters for the Pokemon list
 * @returns React Query result with parsed NamedAPIResourceList data
 */
export function usePokemonListParsed(params?: PokemonListParams) {
  return usePokemonList(params, {
    query: {
      select: (data) => parseApiResponse<NamedAPIResourceList>(data),
    },
  });
}
